#!/usr/bin/env bash
# This script displays information about subdomains of a given domain

get_subdomain_info() {
    domain="$1"
    subdomain="$2"

    if [[ -z "$subdomain" ]]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        answer=$(dig "$sub.$domain" +short)
        if [[ -n "$answer" ]]; then
            record_type=$(dig "$sub.$domain" | awk '/ANSWER SECTION/{getline; print $4}')
            destination=$(dig "$sub.$domain" | awk '/ANSWER SECTION/{getline; print $5}')
            ttl=$(dig "$sub.$domain" | awk '/ANSWER SECTION/{getline; print $2}')
            echo "The subdomain $sub is a $record_type record and points to $destination (TTL: $ttl)"
        else
            echo "No information found for subdomain $sub.$domain"
        fi
    done
}

get_subdomain_info "$1" "$2"
