#!/usr/bin/env bash
# Installs, configures, and starts the server
apt-get update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
# Define the lines to add
lines_to_add="\
    location /redirect_me {\
        return 301 http://example.com/new_page;\
    }"

# Find the line number where we want to insert the new lines
line_number=$(grep -n "server {" /etc/nginx/sites-available/default | cut -d: -f1)

# Insert the lines into the NGINX configuration file
echo "$lines_to_add" | sudo sed -i "$((line_number + 1))i \\$lines_to_add" /etc/nginx/sites-available/default

# Test NGINX configuration
nginx -t

# Reload NGINX if the test is successful
if nginx -t; then
    sudo nginx -s reload
    echo "NGINX configuration reloaded."
else
    echo "There was an error in the NGINX configuration. Please check and correct it."
fi
