#!/usr/bin/env bash
# Display a list of currently running processes with hierarchy
# Use the 'ps' command to retrieve process information
ps -e -o pid,ppid,user,cmd --forest | awk '{printf "%-13s| %-13s| %-10s| %s\n", $1, $2, $3, $4}'
