#!/usr/bin/env bash
# This script displays numbers from 1 to 20 with corresponding messages.

count=1

while [ $count -le 20 ]; do
    case $count in
        4)
            echo "$count bad luck from china"
            ;;
        9)
            echo "$count bad luck from japan"
            ;;
        17)
            echo "$count bad luck from italy"
            ;;
        *)
            echo $count
            ;;
    esac
    ((count++))
done
