#!/usr/bin/env bash
# Check if running with root privileges
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root or using sudo."
  exit 1
fi

# Backup the original hosts file
cp /etc/hosts ~/hosts.new
# Update localhost to resolve to 127.0.0.2
sed -i 's/127\.0\.0\.1/127\.0\.0\.2/' ~/hosts.new
# Add a new entry for 157.240.11.35 resolving to 8.8.8.8
echo "8.8.8.8 facebook.com" >> ~/hosts.new
#copy the information back to the original hosts file
cp -f ~/hosts.new /etc/hosts
