#!/usr/bin/env bash
# Check if netcat is installed
if ! type nc &> /dev/null; then
    echo "Error: netcat (nc) is not installed. Please install it."
    exit 1
fi
# Specify the port to listen on
port=98
# Use netcat to listen on the specified port
nc -l localhost "$port"
