#!/usr/bin/env bash
#this script configures the container with nginx as user, listen on port 8080 and not to use apt-get remove
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start

